### ISSUE TITLE
好像有些小问题

### ISSUE THREAD

**Issue by Cylkal** [smallnest/leetcode-solutions#1]
3.1 找到字符串中最长的无重复字符子串
示例三输出：1 -> 3

**Comment by Cylkal** [comment]
5.2 旋转字符串
原文：例如, 若 s = ′ abcde ′ ，在旋转一次之后结果就是 ′ bcdea ′ 。
abcde前面多了个空格

**Comment by Cylkal** [comment]
7.2 有效的括号
输入: s = s = "(]" -> s = "(]"
输出: true -> false

**Comment by smallnest** [comment]
thanks.
the above bugs have been fixed

**Comment by Cylkal** [comment]
代码 8.1: 数组中的第 K 个最大元素
第8行 `func (h MinHeap) Less(i, j int) bool { return h[i] < h[j] }`
应该是最大堆，所以是 `return h[i] > h[j]`

**Comment by smallnest** [comment]
> 代码 8.1: 数组中的第 K 个最大元素 第8行 `func (h MinHeap) Less(i, j int) bool { return h[i] < h[j] }` 应该是最大堆，所以是 `return h[i] > h[j]`

标题应该写最小堆

**Comment by smallnest** [comment]
> > 代码 8.1: 数组中的第 K 个最大元素 第8行 `func (h MinHeap) Less(i, j int) bool { return h[i] < h[j] }` 应该是最大堆，所以是 `return h[i] > h[j]`
> 
> 标题应该写最小堆

今天写一篇文章的时候也刚发现
